package main

// The checks that keep a byte mover from becoming an SSRF primitive.
//
// This file is the reason the downloader is a separate container. Everything
// else in the system reaches the internet through an identity's proxy, and
// dtk.urls.parse deliberately does not resolve DNS because that proxy is the
// backstop. The downloader dials CDNs directly, so it has no backstop and has
// to carry its own: a host allowlist matched on a label boundary, and a check
// on the address actually being dialed rather than on the name that was typed.
//
// The allowlist itself is NOT defined here. It arrives with each job, because
// the main service owns policy and this process owns execution; two copies of
// one list is how the copy nobody edits becomes the one that is enforced.

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
)

// allowedHost reports whether host sits inside one of the allowed registrable
// domains.
//
// Matched on a label boundary, which is the whole point: a plain
// strings.HasSuffix(host, "tiktok.com") accepts eviltiktok.com, and checking
// only ".tiktok.com" misses the apex.
func allowedHost(host string, domains []string) bool {
	name := strings.ToLower(strings.TrimSuffix(strings.Trim(host, "[]"), "."))
	if name == "" {
		return false
	}
	for _, raw := range domains {
		domain := strings.ToLower(strings.TrimSuffix(strings.TrimSpace(raw), "."))
		if domain == "" {
			continue
		}
		if name == domain || strings.HasSuffix(name, "."+domain) {
			return true
		}
	}
	return false
}

// routableIP reports whether ip is a public address this service may dial.
//
// The negative list is long on purpose. "Not loopback and not RFC1918" leaves
// CGNAT, the link-local metadata address every cloud provider serves on
// 169.254.169.254, IPv6 unique-local, and the reserved 240/4 block - each of
// which is a working path to something inside the host's network.
func routableIP(ip net.IP) bool {
	if ip == nil {
		return false
	}
	if ip.IsUnspecified() || ip.IsLoopback() || ip.IsPrivate() ||
		ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() ||
		ip.IsInterfaceLocalMulticast() || ip.IsMulticast() {
		return false
	}
	// To4 is non-nil for IPv4-mapped IPv6 as well, so ::ffff:10.0.0.1 lands
	// here rather than sliding through the v6 branch below.
	if v4 := ip.To4(); v4 != nil {
		switch {
		case v4[0] == 0: // 0.0.0.0/8, "this network"
			return false
		case v4[0] == 100 && v4[1]&0xc0 == 64: // 100.64.0.0/10, carrier NAT
			return false
		case v4[0] == 192 && v4[1] == 0 && v4[2] == 0: // 192.0.0.0/24, IETF protocol assignments
			return false
		case v4[0] == 192 && v4[1] == 0 && v4[2] == 2: // 192.0.2.0/24, TEST-NET-1
			return false
		case v4[0] == 198 && v4[1]&0xfe == 18: // 198.18.0.0/15, benchmarking
			return false
		case v4[0] == 198 && v4[1] == 51 && v4[2] == 100: // 198.51.100.0/24, TEST-NET-2
			return false
		case v4[0] == 203 && v4[1] == 0 && v4[2] == 113: // 203.0.113.0/24, TEST-NET-3
			return false
		case v4[0] >= 240: // 240.0.0.0/4 reserved, and 255.255.255.255 with it
			return false
		}
		return true
	}
	if len(ip) != net.IPv6len {
		return false
	}
	// 2001:db8::/32, the documentation prefix.
	if ip[0] == 0x20 && ip[1] == 0x01 && ip[2] == 0x0d && ip[3] == 0xb8 {
		return false
	}
	return true
}

// dialGuard refuses a connection to any address that is not publicly routable.
//
// This is a net.Dialer Control hook, which runs after DNS resolution with the
// address the kernel is about to connect to. Checking the hostname instead
// would leave the classic rebinding gap: a name that resolves to a CDN when it
// is validated and to 127.0.0.1 a moment later when it is dialed.
func dialGuard(_, address string, _ syscall.RawConn) error {
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return fmt.Errorf("refusing to dial %q: %w", address, err)
	}
	if ip := net.ParseIP(host); !routableIP(ip) {
		return fmt.Errorf("refusing to dial %s: not a routable public address", host)
	}
	return nil
}

// segmentPattern is what a single path component may look like.
//
// Filenames are generated by the main service, never taken from the CDN, so
// this is a check on our own code rather than on a hostile input - which is
// exactly why it is worth having: the day someone passes a platform-supplied
// name through, this is what refuses it.
var segmentPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$`)

func safeSegment(segment string) bool {
	return segmentPattern.MatchString(segment) && !strings.Contains(segment, "..")
}

// safeJoin builds a path under root, refusing anything that could leave it.
//
// Both halves matter. The per-segment check refuses "..", a leading dot and
// separators of any kind; the prefix check on the result refuses whatever the
// first check failed to imagine, including a root that is itself a symlink
// target the caller did not expect.
func safeJoin(root string, parts ...string) (string, error) {
	for _, part := range parts {
		if !safeSegment(part) {
			return "", fmt.Errorf("unsafe path segment %q", part)
		}
	}
	cleanRoot := filepath.Clean(root)
	joined := filepath.Join(append([]string{cleanRoot}, parts...)...)
	if joined != cleanRoot && !strings.HasPrefix(joined, cleanRoot+string(os.PathSeparator)) {
		return "", fmt.Errorf("path escapes the media root")
	}
	return joined, nil
}

// acceptableType reports whether a Content-Type header matches what the job
// said to expect.
//
// The prefixes come from the job, not from here. A CDN that answers
// application/octet-stream for an mp4 is a policy question - do we trust the
// extension? - and policy belongs to the main service.
func acceptableType(header string, accept []string) bool {
	value := strings.ToLower(strings.TrimSpace(header))
	if index := strings.IndexByte(value, ';'); index >= 0 {
		value = strings.TrimSpace(value[:index])
	}
	if value == "" {
		// No Content-Type at all is not "anything goes".
		return false
	}
	for _, prefix := range accept {
		prefix = strings.ToLower(strings.TrimSpace(prefix))
		if prefix != "" && strings.HasPrefix(value, prefix) {
			return true
		}
	}
	return false
}
